# TEST CONFIGURATION - For quick experiment validation
# This config runs a minimal experiment to test the pipeline without long waits

# path to the task data directory
data_dir: "data"
preprocess_data: False

goal: null
eval: null

log_dir: logs
workspace_dir: workspaces

# whether to copy the data to the workspace directory (otherwise it will be symlinked)
copy_data: True

exp_name: test_run # a random experiment name will be generated if not provided

# settings for code execution - REDUCED TIMEOUT FOR TESTING
exec:
  timeout: 300 # 5 minutes instead of 1 hour
  agent_file_name: runfile.py
  format_tb_ipython: False

generate_report: True
# LLM settings for final report from journal
report:
  model: gpt-4o-2024-11-20
  temp: 1.0

experiment:
  num_syn_datasets: 1

debug:
  stage4: False

# agent hyperparams - MINIMAL SETTINGS FOR TESTING
agent:
  type: parallel
  num_workers: 2 # Reduced from 4 to 2
  stages:
    stage1_max_iters: 3 # Reduced from 20 to 3
    stage2_max_iters: 2 # Reduced from 12 to 2
    stage3_max_iters: 2 # Reduced from 12 to 2
    stage4_max_iters: 2 # Reduced from 18 to 2
  # how many improvement iterations to run
  steps: 2 # Reduced from 5 to 2
  # whether to instruct the agent to use CV (set to 1 to disable)
  k_fold_validation: 1
  multi_seed_eval:
    num_seeds: 1 # Reduced from 3 to 1 - SINGLE SEED FOR TESTING
  # whether to instruct the agent to generate a prediction function
  expose_prediction: False
  # whether to provide the agent with a preview of the data
  data_preview: False

  # LLM settings for coding
  code:
    model: claude-3-5-sonnet-20241022
    temp: 1.0
    max_tokens: 12000

  # LLM settings for evaluating program output / tracebacks
  feedback:
    model: gpt-4o-2024-11-20
    temp: 0.5
    max_tokens: 8192

  vlm_feedback:
    model: gpt-4o-2024-11-20
    temp: 0.5
    max_tokens: null

  search:
    max_debug_depth: 2 # Reduced from 3 to 2
    debug_prob: 0.3 # Reduced from 0.5 to 0.3
    num_drafts: 2 # Reduced from 3 to 2
